---
# tasks file for hswong3i.php

- name: apt-add-repository
  apt_repository:
    repo="{{ item }}"
    state=present
  with_items:
    - ppa:ondrej/php-7.0
  tags: hswong3i.php

- name: apt-get install
  apt:
    name="{{ item }}"
    state=latest
  with_items:
    - php7.0-cli
    - php7.0-curl
    - php7.0-gd
    - php7.0-imap
    - php7.0-intl
    - php7.0-json
    - php7.0-ldap
    - php7.0-mysql
    - php7.0-opcache
    - php7.0-pgsql
    - php7.0-snmp
    - php7.0-sqlite3
    - php7.0-tidy
  tags: hswong3i.php

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/php/7.0/cli/php.ini.j2', dest: '/etc/php/7.0/cli/php.ini',  owner: 'root', group: 'root', mode: '0644' }
  tags: hswong3i.php
