---
# tasks file for hswong3i.php

- name: apt-add-repository
  apt_repository:
    repo="{{ item }}"
    state=present
  with_items:
    - ppa:ondrej/php-7.0
  tags: hswong3i.php

- name: apt-get install
  apt:
    name="{{ item }}"
    state=latest
  with_items:
    - php-apcu
    - php-cli
    - php-curl
    - php-gd
    - php-imap
    - php-intl
    - php-json
    - php-ldap
    - php-mysql
    - php-opcache
    - php-pgsql
    - php-snmp
    - php-sqlite3
    - php-tidy
  tags: hswong3i.php

- name: copy templates
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ item.owner }}
    group={{ item.group }}
    mode={{ item.mode }}
  with_items:
    - { src: 'etc/php/7.0/cli/php.ini.j2', dest: '/etc/php/7.0/cli/php.ini',  owner: 'root', group: 'root', mode: '0644' }
  tags: hswong3i.php
