---
# tasks file for hswong3i.php

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: hswong3i.php

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_repository }}"
  notify: restart php
  tags: hswong3i.php

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt }}"
  notify: restart php
  tags: hswong3i.php

- name: prepare files
  file:
    dest: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "/etc/php", owner: "root", group: "root", mode: "0755", state: "directory" }
    - { dest: "/run/php", owner: "www-data", group: "www-data", mode: "0755", state: "directory" }
  notify: restart php
  tags: hswong3i.php

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ _php_template }}"
  notify: restart php
  tags: hswong3i.php
