---
# handlers file for hswong3i.php

- name: restart php
  service: 
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: php5.6-fpm, state: "restarted" }
    - { name: php7.0-fpm, state: "restarted" }
